In [11]:
import torch

a = torch.randn(2, 3, 4)
a, a.shape

(tensor([[[-2.3230, -0.5764, -0.1289, -2.2407],
          [-0.8571, -1.0422, -0.9864, -1.1853],
          [-0.8108, -0.7362,  1.6342, -1.0224]],
 
         [[-0.0508,  1.0152,  0.1941,  0.3850],
          [-1.3203, -0.2952,  0.2954, -0.4107],
          [-0.9173,  1.2634, -0.1498, -1.0821]]]),
 torch.Size([2, 3, 4]))

In [12]:
a = a[:,-1,:]
a

tensor([[-0.8108, -0.7362,  1.6342, -1.0224],
        [-0.9173,  1.2634, -0.1498, -1.0821]])

In [21]:
a.view(-1, 4)

tensor([[-0.8108, -0.7362,  1.6342, -1.0224],
        [-0.9173,  1.2634, -0.1498, -1.0821]])